# Generated by Django 4.0.4 on 2022-04-17 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('mobileno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(max_length=20)),
                ('Identity_card_number', models.IntegerField()),
                ('driving_licence_no', models.CharField(max_length=20)),
                ('bank_ac_no', models.IntegerField()),
                ('creditcard_no', models.IntegerField()),
                ('atmcard_no', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
