# Generated by Django 4.0.4 on 2022-04-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='profileimg'),
        ),
    ]
