# Generated by Django 4.0.4 on 2022-04-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_userinfo_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_image',
        ),
    ]
